// stats.js

const miamiHeat = {
    teamStats: {
        wins: 46, // Example values, replace with actual data
        losses: 36,
        pointsPerGame: 110.2,
        reboundsPerGame: 42.5,
        assistsPerGame: 25.1,
        fieldGoalPercentage: 0.47,
        threePointPercentage: 0.36,
        freeThrowPercentage: 0.82,
    },
    playerStats: [
        {
            name: "Jimmy Butler",
            position: "Forward",
            pointsPerGame: 22.9,
            reboundsPerGame: 5.9,
            assistsPerGame: 5.3,
            fieldGoalPercentage: 0.52,
            threePointPercentage: 0.35,
        },
        {
            name: "Bam Adebayo",
            position: "Center",
            pointsPerGame: 19.3,
            reboundsPerGame: 10.4,
            assistsPerGame: 3.9,
            fieldGoalPercentage: 0.54,
            threePointPercentage: 0.16,
        },
        {
            name: "Tyler Herro",
            position: "Guard",
            pointsPerGame: 20.7,
            reboundsPerGame: 5.0,
            assistsPerGame: 4.0,
            fieldGoalPercentage: 0.44,
            threePointPercentage: 0.38,
        },
        {
            name: "Kyle Lowry",
            position: "Guard",
            pointsPerGame: 11.2,
            reboundsPerGame: 4.1,
            assistsPerGame: 5.2,
            fieldGoalPercentage: 0.40,
            threePointPercentage: 0.33,
        },
        {
            name: "Duncan Robinson",
            position: "Forward",
            pointsPerGame: 12.9,
            reboundsPerGame: 3.1,
            assistsPerGame: 2.1,
            fieldGoalPercentage: 0.42,
            threePointPercentage: 0.37,
        },
        {
          name: "Caleb Martin",
          position: "Forward",
          pointsPerGame: 10.0,
          reboundsPerGame: 4.8,
          assistsPerGame: 1.6,
          fieldGoalPercentage: 0.49,
          threePointPercentage: 0.34,
        },
        {
          name: "Nikola Jovic",
          position: "Forward",
          pointsPerGame: 5.5,
          reboundsPerGame: 2.1,
          assistsPerGame: 0.7,
          fieldGoalPercentage: 0.44,
          threePointPercentage: 0.39,
        },
        {
          name: "Haywood Highsmith",
          position: "Forward",
          pointsPerGame: 4.4,
          reboundsPerGame: 3.5,
          assistsPerGame: 0.8,
          fieldGoalPercentage: 0.43,
          threePointPercentage: 0.33,
        },
        {
          name: "Kevin Love",
          position: "Forward",
          pointsPerGame: 6.9,
          reboundsPerGame: 5.5,
          assistsPerGame: 1.9,
          fieldGoalPercentage: 0.38,
          threePointPercentage: 0.33,
        },
        {
          name: "Josh Richardson",
          position: "Guard",
          pointsPerGame: 9.9,
          reboundsPerGame: 2.8,
          assistsPerGame: 2.7,
          fieldGoalPercentage: 0.45,
          threePointPercentage: 0.35,
        },
        {
          name: "Thomas Bryant",
          position: "Center",
          pointsPerGame: 6.1,
          reboundsPerGame: 3.2,
          assistsPerGame: 0.5,
          fieldGoalPercentage: 0.62,
          threePointPercentage: 0.44,
        },
        {
          name: "Cole Swider",
          position: "Forward",
          pointsPerGame: 1.3,
          reboundsPerGame: 0.8,
          assistsPerGame: 0.3,
          fieldGoalPercentage: 0.40,
          threePointPercentage: 0.33,
        },
        {
          name: "Jamal Cain",
          position: "Forward",
          pointsPerGame: 5.3,
          reboundsPerGame: 2.8,
          assistsPerGame: 0.6,
          fieldGoalPercentage: 0.49,
          threePointPercentage: 0.31,
        },
        {
          name: "R.J. Hampton",
          position: "Guard",
          pointsPerGame: 5.7,
          reboundsPerGame: 2.3,
          assistsPerGame: 1.7,
          fieldGoalPercentage: 0.48,
          threePointPercentage: 0.33,
        },
    ],
};